apiVersion: v1
kind: Service
metadata:
  name: airtrail-web-service
  namespace: airtrail
spec:
  selector:
    app: airtrail-web
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer

