apiVersion: apps/v1
kind: Deployment
metadata:
  name: airtrail-db
  namespace: airtrail
  labels:
    app: airtrail-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airtrail-db
  template:
    metadata:
      labels:
        app: airtrail-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: "{{ db_name }}"
            - name: POSTGRES_USER
              value: "{{ db_user }}"
            - name: POSTGRES_PASSWORD
              value: "{{ db_password }}"
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

