apiVersion: v1
kind: Service
metadata:
  name: airtrail-db-service
  namespace: airtrail
spec:
  selector:
    app: airtrail-db
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP

